# Vagrantfile
Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/jammy64"  # Ubuntu 22.04 LTS
	config.vm.hostname = "YourLoginS"

	config.vm.network "private_network", ip: "192.168.56.110"

	config.vm.provider "virtualbox" do |vb|
	  vb.memory = 4096
	  vb.cpus = 2
	end

	# Provision K3s server
	config.vm.provision "shell", inline: <<-SHELL
	  set -e

	  # Mise à jour
	  apt-get update -y
	  apt-get upgrade -y

	  # K3s server (avec traefik activé par défaut)
	  if ! command -v k3s >/dev/null 2>&1; then
		curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip=192.168.56.110 --bind-address=0.0.0.0 --advertise-address=192.168.56.110" sh -
	  fi

	  # kubectl déjà linké par K3s (/usr/local/bin/kubectl)
	  echo "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> /home/vagrant/.bashrc
	  chown vagrant:vagrant /etc/rancher/k3s/k3s.yaml
	SHELL
  end
