Vagrant.configure("2") do |config|
	# SERVER
	config.vm.define "userS" do |server|
	  server.vm.box = "ubuntu/focal64"
	  server.vm.hostname = "userS"
	  server.vm.network "private_network", ip: "192.168.56.110"
	  server.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
	  end

	  # Dossier partagé pour échanger le token
	  server.vm.synced_folder ".", "/vagrant"

	  server.vm.provision "shell", path: "server.sh"

	  # Après install K3s, on copie le token dans /vagrant
	  server.vm.provision "shell", inline: <<-SHELL
		TOKEN_FILE=/var/lib/rancher/k3s/server/node-token
		if [ -f "$TOKEN_FILE" ]; then
		  cp "$TOKEN_FILE" /vagrant/k3s_token
		  chmod 644 /vagrant/k3s_token
		fi
	  SHELL
	end

	# WORKER
	config.vm.define "userSW" do |worker|
	  worker.vm.box = "ubuntu/focal64"
	  worker.vm.hostname = "userSW"
	  worker.vm.network "private_network", ip: "192.168.56.111"
	  worker.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
	  end

	  worker.vm.synced_folder ".", "/vagrant"
	  worker.vm.provision "shell", inline: <<-SHELL
		TOKEN=$(cat /vagrant/k3s_token)
		/vagrant/agent.sh "$TOKEN"
	  SHELL
	end
  end
