Vagrant.configure("2") do |config|
	config.vm.box = "generic/centos8"

	config.vm.define "lseiberrS" do |control|
	  control.vm.hostname = "lseiberrS"
	  control.vm.network "private_network", ip: "192.168.56.110"
	  control.vm.synced_folder ".", "/vagrant", disabled: false
	  control.vm.provider "virtualbox" do |v|
		  v.name = "lseiberrS"
			   v.gui = false
			   v.memory = "1024"
			   v.cpus = 1
		  end
	  control.vm.provision "shell", path: "server.sh"
	  end

	config.vm.define "lseiberrSW" do |agent|
	  agent.vm.hostname = "lseiberrSW"
	  agent.vm.network "private_network", ip: "192.168.56.111"
	  agent.vm.synced_folder ".", "/vagrant", disabled: false
	  agent.vm.provider "virtualbox" do |v|
		  v.name = "lseiberrSW"
		  v.gui = false
			   v.memory = "1024"
			   v.cpus = 1
		  end
	  agent.vm.provision "shell", path: "agent.sh"
	  end
  end
