apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground-gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitlab.local:8080/root/lseiberr_ception.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
